server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: report
          uri: http://localhost:8082
          predicates:
            - Path=/deviceReports/**, /reportDashboards/**
        - id: device
          uri: http://localhost:8083
          predicates:
            - Path=/devices/**, /deviceDashboards/**
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/notificationHistories/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/deviceReports/**, 
        - id: device
          uri: http://device:8080
          predicates:
            - Path=/devices/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notificationHistories/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
